services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: pizzaclick_frontend_container
    depends_on:
      - db
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host

  db:
    image: postgres:17
    container_name: pizzaclick_db_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: